/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const TeamId = IDL.Text;
export const Position = IDL.Variant({
  'goalkeeper' : IDL.Null,
  'midfielder' : IDL.Null,
  'forward' : IDL.Null,
  'defender' : IDL.Null,
});
export const PlayerId = IDL.Text;
export const Role = IDL.Variant({
  'fan' : IDL.Null,
  'admin' : IDL.Null,
  'player' : IDL.Null,
  'coach' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const MatchId = IDL.Text;
export const Time = IDL.Int;
export const NewsId = IDL.Text;
export const UserId = IDL.Principal;
export const Type = IDL.Variant({
  'alert' : IDL.Null,
  'reminder' : IDL.Null,
  'message' : IDL.Null,
});
export const NotificationId = IDL.Text;
export const VoteId = IDL.Text;
export const T__6 = IDL.Record({
  'voteId' : VoteId,
  'matchId' : MatchId,
  'voterId' : UserId,
  'timestamp' : Time,
  'nomineePlayerId' : PlayerId,
});
export const Status = IDL.Variant({
  'scheduled' : IDL.Null,
  'played' : IDL.Null,
  'live' : IDL.Null,
});
export const T__5 = IDL.Record({
  'status' : Status,
  'homeTeam' : TeamId,
  'date' : Time,
  'matchId' : MatchId,
  'homeScore' : IDL.Nat,
  'awayTeam' : TeamId,
  'awayScore' : IDL.Nat,
  'commentary' : IDL.Vec(IDL.Text),
  'mvpPlayerId' : IDL.Opt(PlayerId),
  'kickoffTime' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const T__4 = IDL.Record({
  'title' : IDL.Text,
  'isPublished' : IDL.Bool,
  'authorId' : IDL.Text,
  'body' : IDL.Text,
  'newsId' : NewsId,
  'timestamp' : Time,
  'photo' : IDL.Opt(ExternalBlob),
});
export const T__3 = IDL.Record({
  'notifType' : Type,
  'userId' : UserId,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
  'notificationId' : NotificationId,
});
export const T__2 = IDL.Record({
  'nickname' : IDL.Text,
  'assists' : IDL.Nat,
  'userId' : IDL.Text,
  'playerId' : PlayerId,
  'name' : IDL.Text,
  'yellowCards' : IDL.Nat,
  'jerseyNumber' : IDL.Nat,
  'isVerified' : IDL.Bool,
  'goals' : IDL.Nat,
  'redCards' : IDL.Nat,
  'matchesPlayed' : IDL.Nat,
  'photo' : IDL.Opt(ExternalBlob),
  'teamId' : TeamId,
  'position' : Position,
});
export const T__1 = IDL.Record({
  'isApproved' : IDL.Bool,
  'area' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'wins' : IDL.Nat,
  'goalsFor' : IDL.Nat,
  'losses' : IDL.Nat,
  'coachId' : IDL.Text,
  'goalsAgainst' : IDL.Nat,
  'teamId' : TeamId,
  'draws' : IDL.Nat,
});
export const T = IDL.Record({
  'area' : IDL.Text,
  'userId' : IDL.Text,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'favoriteTeamId' : IDL.Opt(TeamId),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminAddPlayer' : IDL.Func(
      [TeamId, IDL.Text, IDL.Text, Position, IDL.Nat],
      [PlayerId],
      [],
    ),
  'adminCreateTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TeamId], []),
  'adminCreateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text],
      [IDL.Text],
      [],
    ),
  'approveTeam' : IDL.Func([TeamId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createMVPVote' : IDL.Func([MatchId, PlayerId], [], []),
  'createMatch' : IDL.Func([TeamId, TeamId, Time, IDL.Text], [MatchId], []),
  'createNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NewsId], []),
  'createNotification' : IDL.Func(
      [UserId, Type, IDL.Text],
      [NotificationId],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(TeamId)],
      [],
      [],
    ),
  'createPlayer' : IDL.Func(
      [TeamId, IDL.Text, IDL.Text, Position, IDL.Nat],
      [PlayerId],
      [],
    ),
  'createTeam' : IDL.Func([IDL.Text, IDL.Text], [TeamId], []),
  'deleteNews' : IDL.Func([NewsId], [], []),
  'getAllMVPVotes' : IDL.Func([], [IDL.Vec(T__6)], ['query']),
  'getAllMatches' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
  'getAllNews' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
  'getAllNewsAdmin' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
  'getAllNotifications' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
  'getAllPlayers' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
  'getAllTeams' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMVPVotesByMatch' : IDL.Func([MatchId], [IDL.Vec(T__6)], ['query']),
  'getMatch' : IDL.Func([MatchId], [IDL.Opt(T__5)], ['query']),
  'getMatchesByStatus' : IDL.Func([Status], [IDL.Vec(T__5)], ['query']),
  'getNews' : IDL.Func([NewsId], [IDL.Opt(T__4)], ['query']),
  'getNotificationsByUser' : IDL.Func([UserId], [IDL.Vec(T__3)], ['query']),
  'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(T__2)], ['query']),
  'getPlayersByTeam' : IDL.Func([TeamId], [IDL.Vec(T__2)], ['query']),
  'getTeam' : IDL.Func([TeamId], [IDL.Opt(T__1)], ['query']),
  'getUserIdFromCaller' : IDL.Func([], [IDL.Text], ['query']),
  'getUserProfile' : IDL.Func([UserId], [IDL.Opt(T)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(TeamId)],
      [],
      [],
    ),
  'updateMatchScore' : IDL.Func([MatchId, IDL.Nat, IDL.Nat, Status], [], []),
  'updateNews' : IDL.Func([NewsId, IDL.Text, IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const TeamId = IDL.Text;
  const Position = IDL.Variant({
    'goalkeeper' : IDL.Null,
    'midfielder' : IDL.Null,
    'forward' : IDL.Null,
    'defender' : IDL.Null,
  });
  const PlayerId = IDL.Text;
  const Role = IDL.Variant({
    'fan' : IDL.Null,
    'admin' : IDL.Null,
    'player' : IDL.Null,
    'coach' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const MatchId = IDL.Text;
  const Time = IDL.Int;
  const NewsId = IDL.Text;
  const UserId = IDL.Principal;
  const Type = IDL.Variant({
    'alert' : IDL.Null,
    'reminder' : IDL.Null,
    'message' : IDL.Null,
  });
  const NotificationId = IDL.Text;
  const VoteId = IDL.Text;
  const T__6 = IDL.Record({
    'voteId' : VoteId,
    'matchId' : MatchId,
    'voterId' : UserId,
    'timestamp' : Time,
    'nomineePlayerId' : PlayerId,
  });
  const Status = IDL.Variant({
    'scheduled' : IDL.Null,
    'played' : IDL.Null,
    'live' : IDL.Null,
  });
  const T__5 = IDL.Record({
    'status' : Status,
    'homeTeam' : TeamId,
    'date' : Time,
    'matchId' : MatchId,
    'homeScore' : IDL.Nat,
    'awayTeam' : TeamId,
    'awayScore' : IDL.Nat,
    'commentary' : IDL.Vec(IDL.Text),
    'mvpPlayerId' : IDL.Opt(PlayerId),
    'kickoffTime' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const T__4 = IDL.Record({
    'title' : IDL.Text,
    'isPublished' : IDL.Bool,
    'authorId' : IDL.Text,
    'body' : IDL.Text,
    'newsId' : NewsId,
    'timestamp' : Time,
    'photo' : IDL.Opt(ExternalBlob),
  });
  const T__3 = IDL.Record({
    'notifType' : Type,
    'userId' : UserId,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
    'notificationId' : NotificationId,
  });
  const T__2 = IDL.Record({
    'nickname' : IDL.Text,
    'assists' : IDL.Nat,
    'userId' : IDL.Text,
    'playerId' : PlayerId,
    'name' : IDL.Text,
    'yellowCards' : IDL.Nat,
    'jerseyNumber' : IDL.Nat,
    'isVerified' : IDL.Bool,
    'goals' : IDL.Nat,
    'redCards' : IDL.Nat,
    'matchesPlayed' : IDL.Nat,
    'photo' : IDL.Opt(ExternalBlob),
    'teamId' : TeamId,
    'position' : Position,
  });
  const T__1 = IDL.Record({
    'isApproved' : IDL.Bool,
    'area' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'wins' : IDL.Nat,
    'goalsFor' : IDL.Nat,
    'losses' : IDL.Nat,
    'coachId' : IDL.Text,
    'goalsAgainst' : IDL.Nat,
    'teamId' : TeamId,
    'draws' : IDL.Nat,
  });
  const T = IDL.Record({
    'area' : IDL.Text,
    'userId' : IDL.Text,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'favoriteTeamId' : IDL.Opt(TeamId),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminAddPlayer' : IDL.Func(
        [TeamId, IDL.Text, IDL.Text, Position, IDL.Nat],
        [PlayerId],
        [],
      ),
    'adminCreateTeam' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [TeamId], []),
    'adminCreateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text],
        [IDL.Text],
        [],
      ),
    'approveTeam' : IDL.Func([TeamId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createMVPVote' : IDL.Func([MatchId, PlayerId], [], []),
    'createMatch' : IDL.Func([TeamId, TeamId, Time, IDL.Text], [MatchId], []),
    'createNews' : IDL.Func([IDL.Text, IDL.Text, IDL.Bool], [NewsId], []),
    'createNotification' : IDL.Func(
        [UserId, Type, IDL.Text],
        [NotificationId],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(TeamId)],
        [],
        [],
      ),
    'createPlayer' : IDL.Func(
        [TeamId, IDL.Text, IDL.Text, Position, IDL.Nat],
        [PlayerId],
        [],
      ),
    'createTeam' : IDL.Func([IDL.Text, IDL.Text], [TeamId], []),
    'deleteNews' : IDL.Func([NewsId], [], []),
    'getAllMVPVotes' : IDL.Func([], [IDL.Vec(T__6)], ['query']),
    'getAllMatches' : IDL.Func([], [IDL.Vec(T__5)], ['query']),
    'getAllNews' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
    'getAllNewsAdmin' : IDL.Func([], [IDL.Vec(T__4)], ['query']),
    'getAllNotifications' : IDL.Func([], [IDL.Vec(T__3)], ['query']),
    'getAllPlayers' : IDL.Func([], [IDL.Vec(T__2)], ['query']),
    'getAllTeams' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(T)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMVPVotesByMatch' : IDL.Func([MatchId], [IDL.Vec(T__6)], ['query']),
    'getMatch' : IDL.Func([MatchId], [IDL.Opt(T__5)], ['query']),
    'getMatchesByStatus' : IDL.Func([Status], [IDL.Vec(T__5)], ['query']),
    'getNews' : IDL.Func([NewsId], [IDL.Opt(T__4)], ['query']),
    'getNotificationsByUser' : IDL.Func([UserId], [IDL.Vec(T__3)], ['query']),
    'getPlayer' : IDL.Func([PlayerId], [IDL.Opt(T__2)], ['query']),
    'getPlayersByTeam' : IDL.Func([TeamId], [IDL.Vec(T__2)], ['query']),
    'getTeam' : IDL.Func([TeamId], [IDL.Opt(T__1)], ['query']),
    'getUserIdFromCaller' : IDL.Func([], [IDL.Text], ['query']),
    'getUserProfile' : IDL.Func([UserId], [IDL.Opt(T)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationAsRead' : IDL.Func([NotificationId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Role, IDL.Text, IDL.Opt(TeamId)],
        [],
        [],
      ),
    'updateMatchScore' : IDL.Func([MatchId, IDL.Nat, IDL.Nat, Status], [], []),
    'updateNews' : IDL.Func([NewsId, IDL.Text, IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };