/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type MatchId = string;
export type NewsId = string;
export type NotificationId = string;
export type PlayerId = string;
export type Position = { 'goalkeeper' : null } |
  { 'midfielder' : null } |
  { 'forward' : null } |
  { 'defender' : null };
export type Role = { 'fan' : null } |
  { 'admin' : null } |
  { 'player' : null } |
  { 'coach' : null };
export type Status = { 'scheduled' : null } |
  { 'played' : null } |
  { 'live' : null };
export interface T {
  'area' : string,
  'userId' : string,
  'name' : string,
  'role' : Role,
  'email' : string,
  'favoriteTeamId' : [] | [TeamId],
  'phone' : string,
}
export interface T__1 {
  'isApproved' : boolean,
  'area' : string,
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'wins' : bigint,
  'goalsFor' : bigint,
  'losses' : bigint,
  'coachId' : string,
  'goalsAgainst' : bigint,
  'teamId' : TeamId,
  'draws' : bigint,
}
export interface T__2 {
  'nickname' : string,
  'assists' : bigint,
  'userId' : string,
  'playerId' : PlayerId,
  'name' : string,
  'yellowCards' : bigint,
  'jerseyNumber' : bigint,
  'isVerified' : boolean,
  'goals' : bigint,
  'redCards' : bigint,
  'matchesPlayed' : bigint,
  'photo' : [] | [ExternalBlob],
  'teamId' : TeamId,
  'position' : Position,
}
export interface T__3 {
  'notifType' : Type,
  'userId' : UserId,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
  'notificationId' : NotificationId,
}
export interface T__4 {
  'title' : string,
  'isPublished' : boolean,
  'authorId' : string,
  'body' : string,
  'newsId' : NewsId,
  'timestamp' : Time,
  'photo' : [] | [ExternalBlob],
}
export interface T__5 {
  'status' : Status,
  'homeTeam' : TeamId,
  'date' : Time,
  'matchId' : MatchId,
  'homeScore' : bigint,
  'awayTeam' : TeamId,
  'awayScore' : bigint,
  'commentary' : Array<string>,
  'mvpPlayerId' : [] | [PlayerId],
  'kickoffTime' : string,
}
export interface T__6 {
  'voteId' : VoteId,
  'matchId' : MatchId,
  'voterId' : UserId,
  'timestamp' : Time,
  'nomineePlayerId' : PlayerId,
}
export type TeamId = string;
export type Time = bigint;
export type Type = { 'alert' : null } |
  { 'reminder' : null } |
  { 'message' : null };
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VoteId = string;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminAddPlayer' : ActorMethod<
    [TeamId, string, string, Position, bigint],
    PlayerId
  >,
  'adminCreateTeam' : ActorMethod<[string, string, string], TeamId>,
  'adminCreateUser' : ActorMethod<
    [string, string, string, Role, string],
    string
  >,
  'approveTeam' : ActorMethod<[TeamId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createMVPVote' : ActorMethod<[MatchId, PlayerId], undefined>,
  'createMatch' : ActorMethod<[TeamId, TeamId, Time, string], MatchId>,
  'createNews' : ActorMethod<[string, string, boolean], NewsId>,
  'createNotification' : ActorMethod<[UserId, Type, string], NotificationId>,
  'createOrUpdateUserProfile' : ActorMethod<
    [string, string, string, Role, string, [] | [TeamId]],
    undefined
  >,
  'createPlayer' : ActorMethod<
    [TeamId, string, string, Position, bigint],
    PlayerId
  >,
  'createTeam' : ActorMethod<[string, string], TeamId>,
  'deleteNews' : ActorMethod<[NewsId], undefined>,
  'getAllMVPVotes' : ActorMethod<[], Array<T__6>>,
  'getAllMatches' : ActorMethod<[], Array<T__5>>,
  'getAllNews' : ActorMethod<[], Array<T__4>>,
  'getAllNewsAdmin' : ActorMethod<[], Array<T__4>>,
  'getAllNotifications' : ActorMethod<[], Array<T__3>>,
  'getAllPlayers' : ActorMethod<[], Array<T__2>>,
  'getAllTeams' : ActorMethod<[], Array<T__1>>,
  'getAllUserProfiles' : ActorMethod<[], Array<T>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [T]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMVPVotesByMatch' : ActorMethod<[MatchId], Array<T__6>>,
  'getMatch' : ActorMethod<[MatchId], [] | [T__5]>,
  'getMatchesByStatus' : ActorMethod<[Status], Array<T__5>>,
  'getNews' : ActorMethod<[NewsId], [] | [T__4]>,
  'getNotificationsByUser' : ActorMethod<[UserId], Array<T__3>>,
  'getPlayer' : ActorMethod<[PlayerId], [] | [T__2]>,
  'getPlayersByTeam' : ActorMethod<[TeamId], Array<T__2>>,
  'getTeam' : ActorMethod<[TeamId], [] | [T__1]>,
  'getUserIdFromCaller' : ActorMethod<[], string>,
  'getUserProfile' : ActorMethod<[UserId], [] | [T]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationAsRead' : ActorMethod<[NotificationId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string, Role, string, [] | [TeamId]],
    undefined
  >,
  'updateMatchScore' : ActorMethod<
    [MatchId, bigint, bigint, Status],
    undefined
  >,
  'updateNews' : ActorMethod<[NewsId, string, string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];