/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export type NewsId = string;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface T__1 {
    isApproved: boolean;
    area: string;
    logo?: ExternalBlob;
    name: string;
    wins: bigint;
    goalsFor: bigint;
    losses: bigint;
    coachId: string;
    goalsAgainst: bigint;
    teamId: TeamId;
    draws: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type MatchId = string;
export type TeamId = string;
export interface T__4 {
    title: string;
    isPublished: boolean;
    authorId: string;
    body: string;
    newsId: NewsId;
    timestamp: Time;
    photo?: ExternalBlob;
}
export type UserId = Principal;
export interface T__3 {
    notifType: Type;
    userId: UserId;
    isRead: boolean;
    message: string;
    timestamp: Time;
    notificationId: NotificationId;
}
export type PlayerId = string;
export interface T__2 {
    nickname: string;
    assists: bigint;
    userId: string;
    playerId: PlayerId;
    name: string;
    yellowCards: bigint;
    jerseyNumber: bigint;
    isVerified: boolean;
    goals: bigint;
    redCards: bigint;
    matchesPlayed: bigint;
    photo?: ExternalBlob;
    teamId: TeamId;
    position: Position;
}
export interface T {
    area: string;
    userId: string;
    name: string;
    role: Role;
    email: string;
    favoriteTeamId?: TeamId;
    phone: string;
}
export type NotificationId = string;
export interface T__5 {
    status: Status;
    homeTeam: TeamId;
    date: Time;
    matchId: MatchId;
    homeScore: bigint;
    awayTeam: TeamId;
    awayScore: bigint;
    commentary: Array<string>;
    mvpPlayerId?: PlayerId;
    kickoffTime: string;
}
export interface T__6 {
    voteId: VoteId;
    matchId: MatchId;
    voterId: UserId;
    timestamp: Time;
    nomineePlayerId: PlayerId;
}
export type VoteId = string;
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum Position {
    goalkeeper = "goalkeeper",
    midfielder = "midfielder",
    forward = "forward",
    defender = "defender"
}
export enum Role {
    fan = "fan",
    admin = "admin",
    player = "player",
    coach = "coach"
}
export enum Status {
    scheduled = "scheduled",
    played = "played",
    live = "live"
}
export enum Type {
    alert = "alert",
    reminder = "reminder",
    message = "message"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminAddPlayer(teamId: TeamId, nickname: string, name: string, position: Position, jerseyNumber: bigint): Promise<PlayerId>;
    adminCreateTeam(name: string, area: string, coachName: string): Promise<TeamId>;
    adminCreateUser(name: string, phone: string, email: string, role: Role, area: string): Promise<string>;
    approveTeam(teamId: TeamId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createMVPVote(matchId: MatchId, nomineePlayerId: PlayerId): Promise<void>;
    createMatch(homeTeam: TeamId, awayTeam: TeamId, date: Time, kickoffTime: string): Promise<MatchId>;
    createNews(title: string, body: string, isPublished: boolean): Promise<NewsId>;
    createNotification(userId: UserId, notifType: Type, message: string): Promise<NotificationId>;
    createOrUpdateUserProfile(name: string, phone: string, email: string, role: Role, area: string, favoriteTeamId: TeamId | null): Promise<void>;
    createPlayer(teamId: TeamId, nickname: string, name: string, position: Position, jerseyNumber: bigint): Promise<PlayerId>;
    createTeam(name: string, area: string): Promise<TeamId>;
    deleteNews(newsId: NewsId): Promise<void>;
    getAllMVPVotes(): Promise<Array<T__6>>;
    getAllMatches(): Promise<Array<T__5>>;
    getAllNews(): Promise<Array<T__4>>;
    getAllNewsAdmin(): Promise<Array<T__4>>;
    getAllNotifications(): Promise<Array<T__3>>;
    getAllPlayers(): Promise<Array<T__2>>;
    getAllTeams(): Promise<Array<T__1>>;
    getAllUserProfiles(): Promise<Array<T>>;
    getCallerUserProfile(): Promise<T | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMVPVotesByMatch(matchId: MatchId): Promise<Array<T__6>>;
    getMatch(matchId: MatchId): Promise<T__5 | null>;
    getMatchesByStatus(status: Status): Promise<Array<T__5>>;
    getNews(newsId: NewsId): Promise<T__4 | null>;
    getNotificationsByUser(userId: UserId): Promise<Array<T__3>>;
    getPlayer(playerId: PlayerId): Promise<T__2 | null>;
    getPlayersByTeam(teamId: TeamId): Promise<Array<T__2>>;
    getTeam(teamId: TeamId): Promise<T__1 | null>;
    getUserIdFromCaller(): Promise<string>;
    getUserProfile(userId: UserId): Promise<T | null>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationAsRead(notificationId: NotificationId): Promise<void>;
    saveCallerUserProfile(name: string, phone: string, email: string, role: Role, area: string, favoriteTeamId: TeamId | null): Promise<void>;
    updateMatchScore(matchId: MatchId, homeScore: bigint, awayScore: bigint, status: Status): Promise<void>;
    updateNews(newsId: NewsId, title: string, body: string, isPublished: boolean): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, MatchId as _MatchId, NewsId as _NewsId, NotificationId as _NotificationId, PlayerId as _PlayerId, Position as _Position, Role as _Role, Status as _Status, T as _T, T__1 as _T__1, T__2 as _T__2, T__3 as _T__3, T__4 as _T__4, T__5 as _T__5, TeamId as _TeamId, Time as _Time, Type as _Type, UserId as _UserId, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminAddPlayer(arg0: TeamId, arg1: string, arg2: string, arg3: Position, arg4: bigint): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddPlayer(arg0, arg1, arg2, to_candid_Position_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddPlayer(arg0, arg1, arg2, to_candid_Position_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async adminCreateTeam(arg0: string, arg1: string, arg2: string): Promise<TeamId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateTeam(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateTeam(arg0, arg1, arg2);
            return result;
        }
    }
    async adminCreateUser(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateUser(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateUser(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async approveTeam(arg0: TeamId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTeam(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTeam(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createMVPVote(arg0: MatchId, arg1: PlayerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMVPVote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMVPVote(arg0, arg1);
            return result;
        }
    }
    async createMatch(arg0: TeamId, arg1: TeamId, arg2: Time, arg3: string): Promise<MatchId> {
        if (this.processError) {
            try {
                const result = await this.actor.createMatch(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMatch(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async createNews(arg0: string, arg1: string, arg2: boolean): Promise<NewsId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNews(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNews(arg0, arg1, arg2);
            return result;
        }
    }
    async createNotification(arg0: UserId, arg1: Type, arg2: string): Promise<NotificationId> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, to_candid_Type_n14(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, to_candid_Type_n14(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createOrUpdateUserProfile(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string, arg5: TeamId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async createPlayer(arg0: TeamId, arg1: string, arg2: string, arg3: Position, arg4: bigint): Promise<PlayerId> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlayer(arg0, arg1, arg2, to_candid_Position_n8(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlayer(arg0, arg1, arg2, to_candid_Position_n8(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async createTeam(arg0: string, arg1: string): Promise<TeamId> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeam(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeam(arg0, arg1);
            return result;
        }
    }
    async deleteNews(arg0: NewsId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNews(arg0);
            return result;
        }
    }
    async getAllMVPVotes(): Promise<Array<T__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMVPVotes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMVPVotes();
            return result;
        }
    }
    async getAllMatches(): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMatches();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMatches();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNews(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNews();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNews();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsAdmin(): Promise<Array<T__4>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsAdmin();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsAdmin();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNotifications(): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNotifications();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNotifications();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllPlayers(): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPlayers();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPlayers();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeams(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeams();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeams();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUserProfiles(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfiles();
                return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfiles();
            return from_candid_vec_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMVPVotesByMatch(arg0: MatchId): Promise<Array<T__6>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMVPVotesByMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMVPVotesByMatch(arg0);
            return result;
        }
    }
    async getMatch(arg0: MatchId): Promise<T__5 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatch(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatch(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchesByStatus(arg0: Status): Promise<Array<T__5>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchesByStatus(to_candid_Status_n51(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchesByStatus(to_candid_Status_n51(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNews(arg0: NewsId): Promise<T__4 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNews(arg0);
                return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNews(arg0);
            return from_candid_opt_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotificationsByUser(arg0: UserId): Promise<Array<T__3>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotificationsByUser(arg0);
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotificationsByUser(arg0);
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayer(arg0: PlayerId): Promise<T__2 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayer(arg0);
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayer(arg0);
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlayersByTeam(arg0: TeamId): Promise<Array<T__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlayersByTeam(arg0);
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlayersByTeam(arg0);
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeam(arg0: TeamId): Promise<T__1 | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeam(arg0);
                return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeam(arg0);
            return from_candid_opt_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserIdFromCaller(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserIdFromCaller();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserIdFromCaller();
            return result;
        }
    }
    async getUserProfile(arg0: UserId): Promise<T | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationAsRead(arg0: NotificationId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: string, arg2: string, arg3: Role, arg4: string, arg5: TeamId | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, arg1, arg2, to_candid_Role_n10(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n16(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async updateMatchScore(arg0: MatchId, arg1: bigint, arg2: bigint, arg3: Status): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMatchScore(arg0, arg1, arg2, to_candid_Status_n51(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMatchScore(arg0, arg1, arg2, to_candid_Status_n51(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateNews(arg0: NewsId, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNews(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNews(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Position_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Position): Position {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_T__1_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): Promise<T__1> {
    return await from_candid_record_n40(_uploadFile, _downloadFile, value);
}
async function from_candid_T__2_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__2): Promise<T__2> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_T__3_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__3): T__3 {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
async function from_candid_T__4_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__4): Promise<T__4> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_T__5_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__5): T__5 {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_T_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Type_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Type): Type {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerId]): PlayerId | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TeamId]): TeamId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T]): T | null {
    return value.length === 0 ? null : from_candid_T_n42(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__5]): T__5 | null {
    return value.length === 0 ? null : from_candid_T__5_n18(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__4]): Promise<T__4 | null> {
    return value.length === 0 ? null : await from_candid_T__4_n24(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__2]): Promise<T__2 | null> {
    return value.length === 0 ? null : await from_candid_T__2_n34(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_T__1]): Promise<T__1 | null> {
    return value.length === 0 ? null : await from_candid_T__1_n39(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    homeTeam: _TeamId;
    date: _Time;
    matchId: _MatchId;
    homeScore: bigint;
    awayTeam: _TeamId;
    awayScore: bigint;
    commentary: Array<string>;
    mvpPlayerId: [] | [_PlayerId];
    kickoffTime: string;
}): {
    status: Status;
    homeTeam: TeamId;
    date: Time;
    matchId: MatchId;
    homeScore: bigint;
    awayTeam: TeamId;
    awayScore: bigint;
    commentary: Array<string>;
    mvpPlayerId?: PlayerId;
    kickoffTime: string;
} {
    return {
        status: from_candid_Status_n20(_uploadFile, _downloadFile, value.status),
        homeTeam: value.homeTeam,
        date: value.date,
        matchId: value.matchId,
        homeScore: value.homeScore,
        awayTeam: value.awayTeam,
        awayScore: value.awayScore,
        commentary: value.commentary,
        mvpPlayerId: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.mvpPlayerId)),
        kickoffTime: value.kickoffTime
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    isPublished: boolean;
    authorId: string;
    body: string;
    newsId: _NewsId;
    timestamp: _Time;
    photo: [] | [_ExternalBlob];
}): Promise<{
    title: string;
    isPublished: boolean;
    authorId: string;
    body: string;
    newsId: NewsId;
    timestamp: Time;
    photo?: ExternalBlob;
}> {
    return {
        title: value.title,
        isPublished: value.isPublished,
        authorId: value.authorId,
        body: value.body,
        newsId: value.newsId,
        timestamp: value.timestamp,
        photo: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.photo))
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notifType: _Type;
    userId: _UserId;
    isRead: boolean;
    message: string;
    timestamp: _Time;
    notificationId: _NotificationId;
}): {
    notifType: Type;
    userId: UserId;
    isRead: boolean;
    message: string;
    timestamp: Time;
    notificationId: NotificationId;
} {
    return {
        notifType: from_candid_Type_n31(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp,
        notificationId: value.notificationId
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nickname: string;
    assists: bigint;
    userId: string;
    playerId: _PlayerId;
    name: string;
    yellowCards: bigint;
    jerseyNumber: bigint;
    isVerified: boolean;
    goals: bigint;
    redCards: bigint;
    matchesPlayed: bigint;
    photo: [] | [_ExternalBlob];
    teamId: _TeamId;
    position: _Position;
}): Promise<{
    nickname: string;
    assists: bigint;
    userId: string;
    playerId: PlayerId;
    name: string;
    yellowCards: bigint;
    jerseyNumber: bigint;
    isVerified: boolean;
    goals: bigint;
    redCards: bigint;
    matchesPlayed: bigint;
    photo?: ExternalBlob;
    teamId: TeamId;
    position: Position;
}> {
    return {
        nickname: value.nickname,
        assists: value.assists,
        userId: value.userId,
        playerId: value.playerId,
        name: value.name,
        yellowCards: value.yellowCards,
        jerseyNumber: value.jerseyNumber,
        isVerified: value.isVerified,
        goals: value.goals,
        redCards: value.redCards,
        matchesPlayed: value.matchesPlayed,
        photo: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.photo)),
        teamId: value.teamId,
        position: from_candid_Position_n36(_uploadFile, _downloadFile, value.position)
    };
}
async function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isApproved: boolean;
    area: string;
    logo: [] | [_ExternalBlob];
    name: string;
    wins: bigint;
    goalsFor: bigint;
    losses: bigint;
    coachId: string;
    goalsAgainst: bigint;
    teamId: _TeamId;
    draws: bigint;
}): Promise<{
    isApproved: boolean;
    area: string;
    logo?: ExternalBlob;
    name: string;
    wins: bigint;
    goalsFor: bigint;
    losses: bigint;
    coachId: string;
    goalsAgainst: bigint;
    teamId: TeamId;
    draws: bigint;
}> {
    return {
        isApproved: value.isApproved,
        area: value.area,
        logo: record_opt_to_undefined(await from_candid_opt_n26(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        wins: value.wins,
        goalsFor: value.goalsFor,
        losses: value.losses,
        coachId: value.coachId,
        goalsAgainst: value.goalsAgainst,
        teamId: value.teamId,
        draws: value.draws
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    area: string;
    userId: string;
    name: string;
    role: _Role;
    email: string;
    favoriteTeamId: [] | [_TeamId];
    phone: string;
}): {
    area: string;
    userId: string;
    name: string;
    role: Role;
    email: string;
    favoriteTeamId?: TeamId;
    phone: string;
} {
    return {
        area: value.area,
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n44(_uploadFile, _downloadFile, value.role),
        email: value.email,
        favoriteTeamId: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.favoriteTeamId)),
        phone: value.phone
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: null;
} | {
    played: null;
} | {
    live: null;
}): Status {
    return "scheduled" in value ? Status.scheduled : "played" in value ? Status.played : "live" in value ? Status.live : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    alert: null;
} | {
    reminder: null;
} | {
    message: null;
}): Type {
    return "alert" in value ? Type.alert : "reminder" in value ? Type.reminder : "message" in value ? Type.message : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    goalkeeper: null;
} | {
    midfielder: null;
} | {
    forward: null;
} | {
    defender: null;
}): Position {
    return "goalkeeper" in value ? Position.goalkeeper : "midfielder" in value ? Position.midfielder : "forward" in value ? Position.forward : "defender" in value ? Position.defender : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fan: null;
} | {
    admin: null;
} | {
    player: null;
} | {
    coach: null;
}): Role {
    return "fan" in value ? Role.fan : "admin" in value ? Role.admin : "player" in value ? Role.player : "coach" in value ? Role.coach : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__5>): Array<T__5> {
    return value.map((x)=>from_candid_T__5_n18(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__4>): Promise<Array<T__4>> {
    return await Promise.all(value.map(async (x)=>await from_candid_T__4_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__3>): Array<T__3> {
    return value.map((x)=>from_candid_T__3_n29(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__2>): Promise<Array<T__2>> {
    return await Promise.all(value.map(async (x)=>await from_candid_T__2_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Promise<Array<T__1>> {
    return await Promise.all(value.map(async (x)=>await from_candid_T__1_n39(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n42(_uploadFile, _downloadFile, x));
}
function to_candid_Position_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): _Position {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_Type_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): _Type {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TeamId | null): [] | [_TeamId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    fan: null;
} | {
    admin: null;
} | {
    player: null;
} | {
    coach: null;
} {
    return value == Role.fan ? {
        fan: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.player ? {
        player: null
    } : value == Role.coach ? {
        coach: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Type): {
    alert: null;
} | {
    reminder: null;
} | {
    message: null;
} {
    return value == Type.alert ? {
        alert: null
    } : value == Type.reminder ? {
        reminder: null
    } : value == Type.message ? {
        message: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    scheduled: null;
} | {
    played: null;
} | {
    live: null;
} {
    return value == Status.scheduled ? {
        scheduled: null
    } : value == Status.played ? {
        played: null
    } : value == Status.live ? {
        live: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Position): {
    goalkeeper: null;
} | {
    midfielder: null;
} | {
    forward: null;
} | {
    defender: null;
} {
    return value == Position.goalkeeper ? {
        goalkeeper: null
    } : value == Position.midfielder ? {
        midfielder: null
    } : value == Position.forward ? {
        forward: null
    } : value == Position.defender ? {
        defender: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
